"""fix activities table

Revision ID: 0525f9ee1220
Revises: d0fa402d38ca
Create Date: 2026-07-31 16:31:10.641360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0525f9ee1220'
down_revision: Union[str, Sequence[str], None] = 'd0fa402d38ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity',
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('distance_meters', sa.Integer(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('total_elevation_gain', sa.Integer(), nullable=True),
    sa.Column('average_pace_seconds', sa.Integer(), nullable=False),
    sa.Column('max_heart_rate', sa.Integer(), nullable=False),
    sa.Column('heart_rate_zone_1_minutes', sa.Integer(), nullable=False),
    sa.Column('heart_rate_zone_2_minutes', sa.Integer(), nullable=False),
    sa.Column('heart_rate_zone_3_minutes', sa.Integer(), nullable=False),
    sa.Column('heart_rate_zone_4_minutes', sa.Integer(), nullable=False),
    sa.Column('heart_rate_zone_5_minutes', sa.Integer(), nullable=False),
    sa.Column('activity_type', sa.String(), nullable=False),
    sa.Column('perceived_effort', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('activity_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activity')
    # ### end Alembic commands ###
