"""change nullable parameter for percived effort col

Revision ID: 3c6b54a44b6e
Revises: 4b6dfbefa430
Create Date: 2026-08-04 23:15:59.993156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c6b54a44b6e'
down_revision: Union[str, Sequence[str], None] = '4b6dfbefa430'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
