"""create plans table

Revision ID: 59ec14721b87
Revises: d805704ea6f3
Create Date: 2026-08-08 14:58:56.941728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59ec14721b87'
down_revision: Union[str, Sequence[str], None] = 'd805704ea6f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TrainingPlan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('goal_race_km', sa.Integer(), nullable=False),
    sa.Column('goal_time_min', sa.Float(), nullable=False),
    sa.Column('race_date', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('weeks_until_race', sa.Integer(), nullable=False),
    sa.Column('training_days_per_week', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), server_default='active', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('TrainingPlan')
    # ### end Alembic commands ###
