"""add strava fields to users

Revision ID: 7a4df3757d31
Revises: 8aa661c0e572
Create Date: 2026-07-29 14:06:40.501428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a4df3757d31'
down_revision: Union[str, Sequence[str], None] = '8aa661c0e572'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('strava_access_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('strava_refresh_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('strava_token_expires_at', sa.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('users', sa.Column('strava_athlete_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'strava_athlete_id')
    op.drop_column('users', 'strava_token_expires_at')
    op.drop_column('users', 'strava_refresh_token')
    op.drop_column('users', 'strava_access_token')
    # ### end Alembic commands ###
