"""create training sessions tables

Revision ID: e13ff3c783ad
Revises: 59ec14721b87
Create Date: 2026-08-08 19:05:25.223266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e13ff3c783ad'
down_revision: Union[str, Sequence[str], None] = '59ec14721b87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TrainingSession',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.String(), nullable=False),
    sa.Column('session_type', sa.String(), nullable=False),
    sa.Column('target_distance', sa.Float(), nullable=False),
    sa.Column('target_pace', sa.Float(), nullable=False),
    sa.Column('target_heart_rate_zone', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('completed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('completed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['TrainingPlan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('TrainingPlan', 'goal_time_min',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('TrainingPlan', 'goal_time_min',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_table('TrainingSession')
    # ### end Alembic commands ###
