"""update plan and session models

Revision ID: fe7ffd43986f
Revises: e13ff3c783ad
Create Date: 2026-08-29 15:42:39.723224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fe7ffd43986f'
down_revision: Union[str, Sequence[str], None] = 'e13ff3c783ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('TrainingSession', 'completed')
    op.drop_column('TrainingSession', 'description')
    op.drop_column('TrainingSession', 'target_heart_rate_zone')
    op.drop_column('TrainingSession', 'completed_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('TrainingSession', sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('TrainingSession', sa.Column('target_heart_rate_zone', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('TrainingSession', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('TrainingSession', sa.Column('completed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
